{
  "TeamMentor_Article": {
    "$": {
      "Metadata_Hash": "1269446204",
      "Content_Hash": "867560712"
    },
    "Metadata": [
      {
        "Id": [
          "2e732e9d-5677-40cc-8e33-c40ceacc056b"
        ],
        "Id_History": [
          "2e732e9d-5677-40cc-8e33-c40ceacc056b,1ab3c221-6915-4f17-8c09-630f903ed709,"
        ],
        "Library_Id": [
          "be5273b1-d682-4361-99d9-6234f2d47eb7"
        ],
        "Title": [
          "Destructors Don't Throw Exceptions"
        ],
        "Category": [
          "Error and Exception Management"
        ],
        "Phase": [
          "Implementation"
        ],
        "Technology": [
          "C++"
        ],
        "Type": [
          "Checklist Item"
        ],
        "DirectLink": [
          "Destructors Don't Throw Exceptions"
        ],
        "Tag": [
          ""
        ],
        "Security_Demand": [
          ""
        ],
        "Author": [
          ""
        ],
        "Priority": [
          ""
        ],
        "Status": [
          ""
        ],
        "Source": [
          "SI"
        ]
      }
    ],
    "Content": [
      {
        "$": {
          "Sanitized": "true",
          "DataType": "Html"
        },
        "Data": [
          "<h1>Applies to</h1>\n  <p>C&#43;&#43;</p>\n  <h1>What to Check For</h1>\n  <p>Verify that destructors don't throw exceptions if they are called when an exception is thrown. The best way to do this is by not throwing exceptions from destructors.</p>\n  <h1>Why</h1>\n  <p>A destructor may be called when an exception is thrown. If a destructor throws an exception after being called from an exception being thrown, the program is likely to terminate. This may result in a denial-of-service vulnerability.</p>\n  <h1>How to Check</h1>\n  <p>Search for destructors. Verify that destructors don't throw exceptions when they are called as a result of other exceptions being thrown. The simplest way to do this is by not throwing exceptions from destructors.</p>\n  <h1>How to Fix</h1>\n  <p>Identify destructors that throw exceptions. Rewrite code so that destructors don't throw exceptions.</p>\n  <h1>Additional Resources</h1>\n  <ul>\n    <li>For more information about not throwing exceptions from destructors, please see <a href=\"https://www.securecoding.cert.org/confluence/display/cplusplus/ERR33-CPP.&#43;Destructors&#43;must&#43;not&#43;throw&#43;exceptions\">https://www.securecoding.cert.org/confluence/display/cplusplus/ERR33-CPP.&#43;Destructors&#43;must&#43;not&#43;throw&#43;exceptions</a></li>\n  </ul>\n  <h1>Related Items</h1>\n  <ul>\n    <li>\n      <a href=\"/article/fd06b089-88ea-43df-bc41-f111a1848116\">Don't Throw Exceptions from Destructors</a>\n      <li>\n        <a href=\"/article/441b4138-1866-442f-8abb-6d05236d6fcb\">Don't Throw Exceptions from Deallocation Functions</a>\n        <li>\n          <a href=\"/article/26a68d55-95e2-4007-bfa6-d1eee30740de\">Deallocation functions don't throw exceptions<br /></a>\n        </li>\n      </li>\n    </li>\n  </ul>"
        ]
      }
    ]
  }
}