<h2>What to Check For</h2>
<p>Verify that deallocation functions don't throw exceptions.</p>
<h2>Why</h2>
<p>Deallocation functions may be called when exceptions are thrown. If a deallocation function throws an exception after being called when an exception is thrown, the program may terminate. This may result in a denial-of-service vulnerability.</p>
<h2>How to Check</h2>
<p>Search for deallocation functions. Verify that deallocation functions don't throw exceptions.</p>
<h2>How to Fix</h2>
<p>Identify deallocation functions that throw exceptions and rewrite them in such a way that they don't throw exceptions.</p>
<h2>Additional Resources</h2>
<ul>
<li>For more information about not throwing exceptions from deallocation functions,  see <a href="https://www.securecoding.cert.org/confluence/display/cplusplus/DCL58-CPP.+Destructors+and+deallocation+functions+must+be+declared+noexcept">https://www.securecoding.cert.org/confluence/display/cplusplus/DCL58-CPP.+Destructors+and+deallocation+functions+must+be+declared+noexcept</a></li>
</ul>
